# bootstrap-local.yml 로컬 환경설정 파일
spring:
  cloud:
    config:
      server:
        native: # 서버 실행시 profile 설정시 native를 지정해야 적용됩니다.
          search-locations: file:///${user.home}/server-configs # window - C:\Users\계정명\server-configs
#        git:
#          uri: file:///${user.home}/server-configs