# local
server:
  port: 9000
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
#        native: # 서버 실행시 profile 설정시 native를 지정해야 적용됩니다.
#          search-locations: file:///C:/Users/user/server-configs # window - C:\Users\계정명\server-configs
        git:
          uri: https://github.com/sisipapa/Springboot-MSA
          search-paths: config-repo/local
encrypt:
  key-store:
    location: classpath:/config-server.jks
    alias: config-server-key
    password: pass123
    type: jks
    secret: pass123
