GET http://localhost:9000/resource/local
Accept: application/json

###

GET http://localhost:9000/resource2/local
Accept: application/json

###

GET http://localhost:9000/gateway/local
Accept: application/json

###

POST http://localhost:9000/encrypt
Content-Type: application/x-www-form-urlencoded

10.10.10.10

###




GET http://localhost:8080/v1/resource/message
Accept: application/json

###

POST http://localhost:8080/actuator/refresh
Accept: application/json

###

GET http://localhost:8080/v1/resource/db
Accept: application/json

###

GET http://localhost:8081/v1/resource2/message
Accept: application/json

###

POST http://localhost:8081/actuator/refresh
Accept: application/json

###

GET http://localhost:9100/v1/member/health
Accept: application/json

###

GET http://localhost:9100/v1/pay/health
Accept: application/json

###

GET http://localhost:9100/v1/product/health
Accept: application/json

###

POST http://localhost:9100/actuator/refresh
Accept: application/json

###

GET http://localhost:9100/v1/resource/db
Accept: application/json

###

GET http://localhost:9100/v1/resource2/message
Accept: application/json

###


