GET http://localhost:9000/resource/prod
Accept: application/json

###

GET http://localhost:9000/resource2/prod
Accept: application/json

###

GET http://localhost:8080/message
Accept: application/json

###

GET http://localhost:8081/message
Accept: application/json

###
