spring:
  profiles: local
#eureka:
#  client:
#    registryFetchIntervalSeconds: 5
#    enabled: true
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true
zuul:
  routes:
    member:
      stripPrefix: false
      path: /v1/member/**
      #url: http://localhost:8080
      serviceId: resource
    resource:
      stripPrefix: false
      path: /v1/resource/**
      #url: http://localhost:8080
      serviceId: resource
    pay:
      stripPrefix: false
      path: /v1/pay/**
      #url: http://localhost:8081
      serviceId: resource2
    resource2:
      stripPrefix: false
      path: /v1/resource2/**
      #url: http://localhost:8080
      serviceId: resource2
    else:
      stripPrefix: false
      path: /v1/**
      #url: http://localhost:8081
      serviceId: resource2