spring:
  profiles: local
  message: Hello Spring MemberService Local Server!!!!!
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown,info
user:
  password: '{cipher}AQBFtSUXeOe9bgCOlU8k/LTWu+/R+jTsU1LaPURGuyLPh4S0eqa+dB9iciWEc67d5al4QCMO4JAcAboD3z26qd6kwhuKW0mnkJ6rJRpsi4xRitS0l6BZpIp4lBayyXdNYdeuKX8/8uWoLtN8x2KTGSlGAotS/XLOhJJFRV9wUeOLWRu1/JsGUns8fLDANLXI+YjIxTgGy2Fn706cBnZOcVSsAKo5Cwszzy0dr7aUYbVBn8X1uM0irVSLAHXaZb8TXCJ4vkFnhzUBxQLcLncsxg15p0lsSD6Rfsd9hXseSgUtrPWDslFaBGVHrW2k2lMo/40YPyrVwiqGFFCVzai9QKGa88W6PF1QYQ/xngF2+c8631G5c0PmpvngsruYMGp/J4Q='