# Resource application.yml
server:
  port: 8080
spring:
  config:
    import: optional:configserver:http://localhost:9000

#spring:
#  profiles:
#    active: local
  application:
    name: resource
management:
  endpoints:
    web:
      exposure:
        include: info, refresh

