spring:
  profiles: prod
  message: Hello Spring ContentsService prod Server!!!!!
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
