spring:
  profiles: prod
zuul:
  routes:
    member:
      stripPrefix: false
      path: /v1/member/**
      serviceId: resource
    pay:
      stripPrefix: false
      path: /v1/pay/**
      serviceId: resource2
    else:
      stripPrefix: false
      path: /v1/**
      serviceId: resource2
#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true
